import { fal } from '@fal-ai/client';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface NanoBananaShotInput {
  /** URL of the original product image */
  imageUrl: string;
  /** Tailored scene/ad prompt generated by the product analyzer */
  prompt: string;
}

interface NanoBananaShotOutput {
  outputUrl: string;
}

// ---------------------------------------------------------------------------
// fal.ai client configuration
// ---------------------------------------------------------------------------

const NANO_BANANA_MODEL = 'fal-ai/nano-banana-2';
const TIMEOUT_MS = 90_000; // Nano Banana can take longer

function ensureFalConfig() {
  const key = process.env['FAL_KEY'] ?? process.env['FAL_API_KEY'] ?? '';
  fal.config({ credentials: key });
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

/**
 * Run Nano Banana 2 via fal.ai.
 *
 * Nano Banana is Google's Gemini-powered image generation model optimized
 * for marketing campaigns, product photography, and product visualization.
 * It takes a product image and a scene description, producing an ad-quality
 * product photo.
 *
 * @throws Error if the API call fails or times out.
 */
export async function runNanoBananaShot(
  params: NanoBananaShotInput
): Promise<NanoBananaShotOutput> {
  ensureFalConfig();
  const startMs = Date.now();

  console.info(
    JSON.stringify({
      event: 'nano_banana_start',
      model: NANO_BANANA_MODEL,
      promptPreview: params.prompt.slice(0, 120),
    })
  );

  const timeoutPromise = new Promise<never>((_, reject) =>
    setTimeout(
      () => reject(new Error(`Nano Banana timed out after ${TIMEOUT_MS}ms`)),
      TIMEOUT_MS
    )
  );

  const apiPromise = fal.subscribe(NANO_BANANA_MODEL as string, {
    input: {
      image_url: params.imageUrl,
      prompt: params.prompt,
    },
    logs: false,
  });

  // Race against timeout
  const result = (await Promise.race([apiPromise, timeoutPromise])) as {
    data: {
      images?: Array<{ url: string }>;
      image?: { url: string };
    };
    requestId: string;
  };

  // Handle both possible output shapes from fal.ai
  const outputUrl =
    result.data?.images?.[0]?.url ?? result.data?.image?.url ?? null;

  if (!outputUrl) {
    throw new Error(
      `Nano Banana returned no output URL. requestId=${result.requestId ?? 'unknown'}`
    );
  }

  console.info(
    JSON.stringify({
      event: 'nano_banana_complete',
      outputUrl,
      durationMs: Date.now() - startMs,
    })
  );

  return { outputUrl };
}
